#!/bin/bash

if [ -f .config/flake8.toml ]; then
  flake8 --format gl-codeclimate --exit-zero --config .config/flake8.toml | jq -c -r '.[]'
else
  curl -sSL https://gitlab.com/megabyte-labs/common/python/-/raw/master/project/.config/flake8.toml > /tmp/flake8.toml
  flake8 --format gl-codeclimate --exit-zero --config /tmp/flake8.toml | jq -c -r '.[]'
fi
